-- ============================================================================
-- geoHELP — schema iniziale Supabase (dev)
-- ----------------------------------------------------------------------------
-- Da eseguire UNA volta nel SQL Editor del progetto geoHELP-dev.
-- Idempotente: usa IF NOT EXISTS / DROP POLICY IF EXISTS dove sensato.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1) profiles — anagrafica base (NON sensibile, in chiaro)
--    Una riga per ogni auth.users.id.
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
    id                       uuid primary key references auth.users(id) on delete cascade,
    email                    text,                  -- copia da auth.users (login)
    first_name               text,                  -- richiesto al primo onboarding
    birth_year               int  check (birth_year is null or (birth_year between 1900 and 2100)),
    gender                   text check (gender in ('M','F','X') or gender is null),
    emergency_contact_name   text,
    emergency_contact_phone  text,
    preferred_language       text not null default 'it' check (preferred_language in ('it','en')),
    created_at               timestamptz not null default now(),
    updated_at               timestamptz not null default now()
);
-- Nota: blood_group è stato spostato su public.medical_data (vedi sotto)
-- in quanto dato sanitario. Migration: 0006_blood_group_to_medical_data.sql

-- ---------------------------------------------------------------------------
-- 2) medical_data — dati sanitari in chiaro (colonne strutturate)
--    Protetti da RLS (auth.uid() = user_id), trasporto HTTPS e consenso
--    esplicito alla liberatoria. Il team admin (service_role) può leggerli
--    in chiaro per finalità di soccorso/supporto, come da informativa.
--
--    Il PIN locale dell'app serve solo come lock per la schermata Dati medici.
--    Reset/cambio PIN NON tocca i dati su Supabase.
-- ---------------------------------------------------------------------------
create table if not exists public.medical_data (
    user_id          uuid primary key references auth.users(id) on delete cascade,
    conditions       text,                  -- codici patologia separati da virgola (ordine urgenza): CA,PO,NE,PA,PB,DIA,IA,IV,AL
    pacemaker        boolean not null default false,
    blood_group      text check (
                          blood_group is null
                          or blood_group in ('A+','A-','B+','B-','AB+','AB-','0+','0-')
                     ),
    allergies        text,                  -- allergie farmacologiche
    therapies        text,                  -- terapie/farmaci in corso
    notes            text,                  -- note libere
    medical_blob_enc text,                  -- LEGACY (vecchio schema cifrato), non più usato dall'app
    enc_version      int not null default 1,
    updated_at       timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 3) consents — storico consensi (privacy / dati sanitari / man down)
-- ---------------------------------------------------------------------------
create table if not exists public.consents (
    id            bigint generated by default as identity primary key,
    user_id       uuid not null references auth.users(id) on delete cascade,
    consent_type  text not null check (consent_type in ('privacy','medical_data','man_down')),
    version       text not null,            -- es. 'v1' oppure '2026-05-12'
    accepted      boolean not null,
    accepted_at   timestamptz not null default now()
);

create index if not exists consents_user_id_idx on public.consents (user_id);
create index if not exists consents_type_idx    on public.consents (consent_type);

-- ---------------------------------------------------------------------------
-- 4) sos_recipients — numeri SMS (sostituisce il Google Sheet pubblico)
--    Lettura: tutti gli utenti autenticati.
--    Scrittura: SOLO dashboard / service_role (per ora non si scrive da app).
-- ---------------------------------------------------------------------------
create table if not exists public.sos_recipients (
    id           bigint generated by default as identity primary key,
    label        text,
    phone        text not null,
    role         text not null check (role in ('primary','backup')),
    active       boolean not null default true,
    sort_order   int not null default 0,
    created_at   timestamptz not null default now(),
    updated_at   timestamptz not null default now()
);

create index if not exists sos_recipients_active_idx on public.sos_recipients (active);
create index if not exists sos_recipients_role_idx   on public.sos_recipients (role);

-- ---------------------------------------------------------------------------
-- 5) sms_events — log statistico SMS (senza contenuto messaggio)
--    channel: manual | mandown
--    message_kind: prepared (solo manual) | initial | trace | lost_signal
--    emergency_type: incident | illness | … | mandown
-- ---------------------------------------------------------------------------
create table if not exists public.sms_events (
    id              bigint generated always as identity primary key,
    user_id         uuid not null references auth.users(id) on delete cascade,
    channel         text not null check (channel in ('manual', 'mandown')),
    message_kind    text not null check (message_kind in ('prepared', 'initial', 'trace', 'lost_signal')),
    emergency_type  text not null check (emergency_type in (
                        'incident', 'illness', 'vehicle', 'lost', 'weather', 'other', 'mandown'
                    )),
    outcome         text not null check (outcome in ('ok', 'failed')),
    dest_count      smallint,
    segment_count   smallint,
    trace_index     smallint check (trace_index is null or (trace_index between 1 and 4)),
    recipient_role  text check (recipient_role is null or recipient_role in ('primary', 'backup')),
    created_at      timestamptz not null default now()
);

create index if not exists sms_events_user_id_idx on public.sms_events (user_id);
create index if not exists sms_events_created_at_idx on public.sms_events (created_at desc);
create index if not exists sms_events_channel_idx on public.sms_events (channel);

-- ============================================================================
-- RLS — Row Level Security
-- ============================================================================
alter table public.profiles       enable row level security;
alter table public.medical_data   enable row level security;
alter table public.consents       enable row level security;
alter table public.sos_recipients enable row level security;
alter table public.sms_events     enable row level security;

-- profiles: ogni utente vede e scrive SOLO la propria riga
drop policy if exists "profiles_select_own"  on public.profiles;
drop policy if exists "profiles_insert_own"  on public.profiles;
drop policy if exists "profiles_update_own"  on public.profiles;
drop policy if exists "profiles_delete_own"  on public.profiles;

create policy "profiles_select_own"
    on public.profiles for select
    using (auth.uid() = id);

create policy "profiles_insert_own"
    on public.profiles for insert
    with check (auth.uid() = id);

create policy "profiles_update_own"
    on public.profiles for update
    using (auth.uid() = id)
    with check (auth.uid() = id);

create policy "profiles_delete_own"
    on public.profiles for delete
    using (auth.uid() = id);

-- medical_data: stessa logica (own user_id)
drop policy if exists "medical_select_own" on public.medical_data;
drop policy if exists "medical_insert_own" on public.medical_data;
drop policy if exists "medical_update_own" on public.medical_data;
drop policy if exists "medical_delete_own" on public.medical_data;

create policy "medical_select_own"
    on public.medical_data for select
    using (auth.uid() = user_id);

create policy "medical_insert_own"
    on public.medical_data for insert
    with check (auth.uid() = user_id);

create policy "medical_update_own"
    on public.medical_data for update
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

create policy "medical_delete_own"
    on public.medical_data for delete
    using (auth.uid() = user_id);

-- consents: ogni utente legge/scrive solo i propri
drop policy if exists "consents_select_own" on public.consents;
drop policy if exists "consents_insert_own" on public.consents;

create policy "consents_select_own"
    on public.consents for select
    using (auth.uid() = user_id);

create policy "consents_insert_own"
    on public.consents for insert
    with check (auth.uid() = user_id);

-- Niente UPDATE/DELETE sui consensi: i consensi sono uno storico immutabile.
-- (Eventuale revoca = nuova riga con accepted = false.)

-- sos_recipients:
-- - SELECT: tutti (anon + authenticated), solo righe active = true.
--   Motivo: i numeri SOS sono dati operativi NON sensibili (oggi sono pubblicati
--   nel CSV Google Sheet), e l'app deve poterli leggere anche prima del login
--   (es. test, futuro fallback SOS "guest"). Sono comunque solo letture.
-- - INSERT/UPDATE/DELETE: nessuno da client (solo service_role / dashboard).
drop policy if exists "sos_recipients_select_authenticated" on public.sos_recipients;
drop policy if exists "sos_recipients_select_active"        on public.sos_recipients;

create policy "sos_recipients_select_active"
    on public.sos_recipients for select
    to authenticated, anon
    using (active = true);

-- sms_events: ogni utente inserisce/legge solo i propri eventi
drop policy if exists "sms_events_select_own" on public.sms_events;
drop policy if exists "sms_events_insert_own" on public.sms_events;

create policy "sms_events_select_own"
    on public.sms_events for select
    using (auth.uid() = user_id);

create policy "sms_events_insert_own"
    on public.sms_events for insert
    with check (auth.uid() = user_id);

-- ============================================================================
-- Triggers
-- ============================================================================

-- 1) Aggiorna automaticamente updated_at su profiles / medical_data / sos_recipients
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at       on public.profiles;
drop trigger if exists trg_medical_data_updated_at   on public.medical_data;
drop trigger if exists trg_sos_recipients_updated_at on public.sos_recipients;

create trigger trg_profiles_updated_at
    before update on public.profiles
    for each row execute function public.set_updated_at();

create trigger trg_medical_data_updated_at
    before update on public.medical_data
    for each row execute function public.set_updated_at();

create trigger trg_sos_recipients_updated_at
    before update on public.sos_recipients
    for each row execute function public.set_updated_at();

-- 2) Crea automaticamente la riga in public.profiles alla registrazione
--    (così l'app non deve fare il "create profile" la prima volta).
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, preferred_language, email)
    values (new.id, 'it', new.email)
    on conflict (id) do update
        set email = excluded.email
        where public.profiles.email is distinct from excluded.email;
    return new;
end;
$$;

drop trigger if exists trg_auth_users_on_signup on auth.users;

create trigger trg_auth_users_on_signup
    after insert on auth.users
    for each row execute function public.handle_new_user();

-- ============================================================================
-- Fine schema.
-- ============================================================================
