package it.geohelp.trek

object TrekTrailCatalog {
    fun trails(): List<TrekTrailRow> = listOf(
        TrekTrailRow(
            comune = "Sestriere",
            sentieroNome = "Passeggiata del Senatore",
            sentieroNumero = "n. 1",
            breveDescrizione = "Passeggiata panoramica partendo da Sestriere.",
            pdfAsset = "trek/pdf/SESTRIERE/1_passeggiata_del_senatore.pdf",
            trkAsset = "trek/trk/SESTRIERE/1_passeggiata_del_senatore.trk",
            startLat = 44.951182,
            startLon = 6.874738,
        ),
        TrekTrailRow(
            comune = "Sestriere",
            sentieroNome = "Sentiero Brugnetti/Sidoti",
            sentieroNumero = "n. 2",
            breveDescrizione = "Vallone del Chisonetto, ex Diga Chisonetto.",
            pdfAsset = "trek/pdf/SESTRIERE/2_sentiero_brugnetti_sidoti_diga_chisonetto.pdf",
            trkAsset = "trek/trk/SESTRIERE/2_sentiero_brugnetti_sidoti_diga_chisonetto.trk",
            startLat = 44.959629,
            startLon = 6.884677,
        ),
        TrekTrailRow(
            comune = "Sestriere",
            sentieroNome = "Sentiero dei Rododendri",
            sentieroNumero = "n. 3",
            breveDescrizione = "Vallone del Chisonetto, ex Diga Chisonetto.",
            pdfAsset = "trek/pdf/SESTRIERE/3_sentiero_dei_rododendri.pdf",
            trkAsset = "trek/trk/SESTRIERE/3_sentiero_dei_rododendri.trk",
            startLat = 44.959608,
            startLon = 6.884779,
        ),
        TrekTrailRow(
            comune = "Sestriere",
            sentieroNome = "Sentiero Dematteis",
            sentieroNumero = "n. 4",
            breveDescrizione = "Vallone del Chisonetto, ex Diga Chisonetto.",
            pdfAsset = "trek/pdf/SESTRIERE/4_sentiero_dematteis.pdf",
            trkAsset = "trek/trk/SESTRIERE/4_sentiero_dematteis.trk",
            startLat = 44.959626,
            startLon = 6.884688,
        ),
        TrekTrailRow(
            comune = "Sestriere",
            sentieroNome = "Sentiero delle Marmotte",
            sentieroNumero = "n. 5",
            breveDescrizione = "Monte Alpette — percorso panoramico.",
            pdfAsset = "trek/pdf/SESTRIERE/5_sentiero_delle_marmotte_monte_alpette.pdf",
            trkAsset = "trek/trk/SESTRIERE/5_sentiero_delle_marmotte_monte_alpette.trk",
            startLat = 44.959644,
            startLon = 6.884600,
        ),
        TrekTrailRow(
            comune = "Sestriere",
            sentieroNome = "Borgata Sestriere",
            sentieroNumero = "n. 6",
            breveDescrizione = "Anello dalla Borgata di Sestriere.",
            pdfAsset = "trek/pdf/SESTRIERE/6_sentiero_borgata_sestriere.pdf",
            trkAsset = "trek/trk/SESTRIERE/6_sentiero_borgata_sestriere.trk",
            startLat = 44.959640,
            startLon = 6.884617,
        ),
        TrekTrailRow(
            comune = "Sestriere",
            sentieroNome = "Champlas du Col - Granges des Alpes",
            sentieroNumero = "n. 7",
            breveDescrizione = "Da Champlas du Col alle Granges des Alpes.",
            pdfAsset = "trek/pdf/SESTRIERE/7_champlas_du_col_granges_des_alpes.pdf",
            trkAsset = "trek/trk/SESTRIERE/7_champlas_du_col_granges_des_alpes.trk",
            startLat = 44.947880,
            startLon = 6.852867,
        ),
        TrekTrailRow(
            comune = "Sestriere",
            sentieroNome = "Sestriere - Chalmettes",
            sentieroNumero = "n. 8",
            breveDescrizione = "Da Sestriere verso le Chalmettes.",
            pdfAsset = "trek/pdf/SESTRIERE/8_sestriere_chalmettes.pdf",
            trkAsset = "trek/trk/SESTRIERE/8_sestriere_chalmettes.trk",
            startLat = 44.956392,
            startLon = 6.868124,
        ),
        TrekTrailRow(
            comune = "Sestriere",
            sentieroNome = "Monte Fraiteve",
            sentieroNumero = "n. 9",
            breveDescrizione = "Da Sestriere al Monte Fraiteve.",
            pdfAsset = "trek/pdf/SESTRIERE/9_sestriere_monte_fraiteve.pdf",
            trkAsset = "trek/trk/SESTRIERE/9_sestriere_monte_fraiteve.trk",
            startLat = 44.959868,
            startLon = 6.875662,
        ),
        TrekTrailRow(
            comune = "Sestriere",
            sentieroNome = "Borgata - Anfiteatro - Rif. Chisonetto",
            sentieroNumero = "n. 10",
            breveDescrizione = "Anello Borgata, Anfiteatro e Rifugio Chisonetto.",
            pdfAsset = "trek/pdf/SESTRIERE/10_borgata_anfiteatro_rif._chisonetto_borgata.pdf",
            trkAsset = "trek/trk/SESTRIERE/10_borgata_anfiteatro_rif._chisonetto_borgata.trk",
            startLat = 44.971417,
            startLon = 6.894779,
        ),
        TrekTrailRow(
            comune = "Sestriere",
            sentieroNome = "Sentiero Bordin Est",
            sentieroNumero = "n. 12e",
            breveDescrizione = "Variante est del Sentiero Bordin.",
            pdfAsset = "trek/pdf/SESTRIERE/12e_sentiero_bordin_est.pdf",
            trkAsset = "trek/trk/SESTRIERE/12e_sentiero_bordin_est.trk",
            startLat = 44.961762,
            startLon = 6.869515,
        ),
        TrekTrailRow(
            comune = "Sestriere",
            sentieroNome = "Sentiero Bordin Ovest",
            sentieroNumero = "n. 12w",
            breveDescrizione = "Variante ovest del Sentiero Bordin.",
            pdfAsset = "trek/pdf/SESTRIERE/12w_sentiero_bordin_ovest.pdf",
            trkAsset = "trek/trk/SESTRIERE/12w_sentiero_bordin_ovest.trk",
            startLat = 44.958240,
            startLon = 6.839644,
        ),
        TrekTrailRow(
            comune = "Sestriere",
            sentieroNome = "Sentiero Natura Luigi XIV",
            sentieroNumero = "n. 14",
            breveDescrizione = "Champlas du Col, sentiero natura.",
            pdfAsset = "trek/pdf/SESTRIERE/14_sentiero_luigi_xiv.pdf",
            trkAsset = "trek/trk/SESTRIERE/14_sentiero_luigi_xiv.trk",
            startLat = 44.950572,
            startLon = 6.856118,
        ),
        TrekTrailRow(
            comune = "Sestriere",
            sentieroNome = "Champlas du Col - Sauze di Cesana",
            sentieroNumero = "n. 15",
            breveDescrizione = "Da Champlas du Col a Sauze di Cesana.",
            pdfAsset = "trek/pdf/SESTRIERE/15_champlas_du_col_sauze_di_cesana.pdf",
            trkAsset = "trek/trk/SESTRIERE/15_champlas_du_col_sauze_di_cesana.trk",
            startLat = 44.947553,
            startLon = 6.852085,
        ),
        TrekTrailRow(
            comune = "Sestriere",
            sentieroNome = "Sestriere - M. Sises - Passo San Giacomo",
            sentieroNumero = "n. 16",
            breveDescrizione = "Tra Sestriere, Monte Sises e Passo San Giacomo.",
            pdfAsset = "trek/pdf/SESTRIERE/16_sestriere_sises_passo_san_giacomo.pdf",
            trkAsset = "trek/trk/SESTRIERE/16_sestriere_sises_passo_san_giacomo.trk",
            startLat = 44.951178,
            startLon = 6.874832,
        ),
        TrekTrailRow(
            comune = "Sestriere",
            sentieroNome = "Monte Rotta - Monte Fraiteve - Colle Basset",
            sentieroNumero = "n. 17",
            breveDescrizione = "Tra Monte Rotta, Fraiteve e Colle Basset.",
            pdfAsset = "trek/pdf/SESTRIERE/17_monterotta_monte_fraiteve_colle_basset.pdf",
            trkAsset = "trek/trk/SESTRIERE/17_monterotta_monte_fraiteve_colle_basset.trk",
            startLat = 44.959675,
            startLon = 6.842131,
        ),
        TrekTrailRow(
            comune = "Sestriere",
            sentieroNome = "Colle Basset - Fraiteve",
            sentieroNumero = "n. 18",
            breveDescrizione = "Dal Colle Basset al Monte Fraiteve.",
            pdfAsset = "trek/pdf/SESTRIERE/18_colle_basset_fraiteve.pdf",
            trkAsset = "trek/trk/SESTRIERE/18_colle_basset_fraiteve.trk",
            startLat = 44.985785,
            startLon = 6.870239,
        ),
        TrekTrailRow(
            comune = "Sestriere",
            sentieroNome = "Colle Basset - Pitre de L'Aigle",
            sentieroNumero = "n. 19",
            breveDescrizione = "Dal Colle Basset a Pitre de L'Aigle.",
            pdfAsset = "trek/pdf/SESTRIERE/19_colle_basset_pitre_de_l_aigle.pdf",
            trkAsset = "trek/trk/SESTRIERE/19_colle_basset_pitre_de_l_aigle.trk",
            startLat = 44.988120,
            startLon = 6.868497,
        ),
        TrekTrailRow(
            comune = "Sestriere",
            sentieroNome = "Borgata - Pattemouche",
            sentieroNumero = "n. 20",
            breveDescrizione = "Tra Borgata e Pattemouche.",
            pdfAsset = "trek/pdf/SESTRIERE/20_borgata_pattemouche.pdf",
            trkAsset = "trek/trk/SESTRIERE/20_borgata_pattemouche.trk",
            startLat = 44.971972,
            startLon = 6.895579,
        ),
        TrekTrailRow(
            comune = "Sestriere",
            sentieroNome = "Strada Bessen Haut",
            sentieroNumero = "n. 21",
            breveDescrizione = "Strada Bessen Haut (1962 m).",
            pdfAsset = "trek/pdf/SESTRIERE/21_strada_bessen_haut.pdf",
            trkAsset = "trek/trk/SESTRIERE/21_strada_bessen_haut.trk",
            startLat = 44.951318,
            startLon = 6.873045,
        ),
        TrekTrailRow(
            comune = "Sestriere",
            sentieroNome = "Sentiero dei Forestali - Colle Basset",
            sentieroNumero = "S.d.F.",
            breveDescrizione = "Sentiero dei Forestali verso Colle Basset.",
            pdfAsset = "trek/pdf/SESTRIERE/s.d.f._sentiero_dei_forestali_colle_basset.pdf",
            trkAsset = "trek/trk/SESTRIERE/s.d.f._sentiero_dei_forestali_colle_basset.trk",
            startLat = 44.964878,
            startLon = 6.880496,
        ),
    )
}
